
// This file has been generated by genreflex with the --capabilities option
static  const char* clnames[] = {
//--Begin tmp/slc6_amd64_gcc530/src/HTTutilities/Jet2TauFakes/src/HTTutilitiesJet2TauFakes/a/HTTutilitiesJet2TauFakes_xr.cc_tmp
 "LCGReflex/IFunctionWrapper",
 "LCGReflex/WrapperTGraph",
 "LCGReflex/WrapperTFormula",
 "LCGReflex/WrapperTH1D",
 "LCGReflex/WrapperTH2F",
 "LCGReflex/WrapperTH2D",
 "LCGReflex/WrapperTH3D",
 "LCGReflex/FakeFactor",
 "LCGReflex/std::map<std::string,std::vector<unsigned long> >",
 "LCGReflex/map<string,vector<unsigned long> >",
 "LCGReflex/std::map<std::string,std::vector<std::vector<unsigned long> > >",
 "LCGReflex/map<string,vector<vector<unsigned long> > >",
//--End   tmp/slc6_amd64_gcc530/src/HTTutilities/Jet2TauFakes/src/HTTutilitiesJet2TauFakes/a/HTTutilitiesJet2TauFakes_xr.cc_tmp
//--Final End
};

extern "C" void SEAL_CAPABILITIES (const char**& names, int& n )
{
names = clnames;
n = sizeof(clnames)/sizeof(char*);
}
